---
title: "Synthetic control"
date: "July 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
### Library
library(sf)
library(ggplot2)
library(tmap)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stargazer)
library(stringr)
library(vtable)
library(haven)
library(ggplot2)
library(expss)
library(gridExtra)
library(ggrepel)
library(labelled)
```


```{r include=FALSE}

  #Load data
  setwd("/Users/maranzazuru/Dropbox/Research/Replication Project/Extracted Files/Data")
  d.rep <- read_dta("FinalDatasetForReplication.dta")
  d.mil <- read_dta("MilitaryBasesByYear.dta")
  d.vic <- read_dta("VictimsByYear.dta")
  d.lb <- read_dta("LB_Analysis.dta")
  
  #Arrange by province and comuna
  d.rep <- d.rep %>% arrange(IDProv, comuna)
  d.rep <- d.rep %>% select(IDProv, comuna, MainSample, DMilitaryPresence, everything())
  
    #Summary key variables in analysis (as in Dofile of tables)
    # Outcome variables:
      #shVictims_70
      #VoteShareNo_pop70
      #VoteShareNo
      #Share_reg70_w2

    #Treatment variables:
      #DMilitaryPresence
      #NEED OTHERS
  
    #Controls  
    #C <- c("share_allende70", "share_alessandri70", "lnDistStgo", "lnDistRegCapital", "Pop70_pthousands", "sh_rural_70")

    #Weights   
    #W <-  Pop70

```

```{r include=FALSE}

  #Library for synthetic control 
  library(haven)
  library(Synth)
  library(SCtools)

  #Create panel for voter turnout
    vtable(d.rep)
    # Controls paper includes:
     C <- c("share_allende70", "share_alessandri70", "lnDistStgo", "lnDistRegCapital", "Pop70_pthousands", "sh_rural_70")
    
    #Controls that are significant in Table 1 (which they try to minimize with FE)
     Cplus <- c("share_up73_congress", "landlocked", "densidad_1970", "churches_pop70", "Pop70", "Houses_pc", "SocialOrg_pop70")
        #Missing turnout in the 70s.

    #Things I believe can be predictive of turnout
     Cplusplus <- c("publicgoods", "index1b", "sh_econactivepop_70", "sh_educ_12more", "sh_unemp_82")
     
     #Y variable: turnout
     Y <- c("Share_reg70_w2", "Turnout70", "Turnout64", "Turnout58", "Turnout52")
    
  #Create database only main variables
    d.syn.turn.wide <- d.rep %>% filter(!(is.na(IDProv))) %>% select((paste(c("IDProv", "comuna", "DMilitaryPresence", Y, C, Cplus, Cplusplus), sep = " , ")))
    
   d.syn.turn <- gather(d.syn.turn.wide, year, turnout, all_of(Y), factor_key=FALSE) %>% 
                 arrange(IDProv, comuna)
    #We should have: 1,470 (good!)

  #Put time variable
  d.syn.turn <- d.syn.turn %>% mutate(
                                year = case_when(
                                year == "Share_reg70_w2" ~ 1988,
                                year == "Turnout70" ~ 1970,
                                year == "Turnout64" ~ 1964,
                                year == "Turnout58" ~ 1958,
                                year == "Turnout52" ~ 1952))
  
  d.syn.turn <- d.syn.turn %>% select(IDProv, comuna, year, turnout, everything()) %>% arrange(IDProv, comuna, year)
  
  #Leave treatment indicator only for 1988
  d.syn.turn <- d.syn.turn %>% mutate(
                               DMilitaryPresence = case_when(
                               year==1970 ~ 0,
                               year==1964 ~ 0,
                               year==1958 ~ 0,
                               year==1952 ~ 0,
                               year==1988 ~ DMilitaryPresence                           
                               ))
  
  #Identified treated comunas
  treat <- unique(d.syn.turn.wide[d.syn.turn.wide$DMilitaryPresence==1,]$comuna)
  control <- unique(d.syn.turn.wide[d.syn.turn.wide$DMilitaryPresence==0,]$comuna)
  
  #Remove control units with missing in all obs for some predictors or turnover values
  idx = which(control %in% c(162, 197, 217, 257, 287, 55, 103, 243, 150, 216, 222, 223,
                             22, 94, 119, 127, 162, 173, 197, 257, 287)) 
  control = control[-idx]

    #Step neededm to make sure runs smoothly
    d.syn.turn[,c("IDProv", C, Cplus, Cplusplus)] <- sapply(d.syn.turn[,c("IDProv", C, Cplus, Cplusplus)],as.numeric)
    d.syn.turn <- as.data.frame(d.syn.turn)
  
  #Data prep for synthetic control
  dataprep_out <- dataprep(
                  foo = d.syn.turn,
                  predictors = c(C, Cplus), #These are the same value across all years
                  predictors.op = "mean",
                  time.predictors.prior = c(1952, 1958, 1964, 1970),
                  special.predictors = list(list("turnout", c(1952, 1958, 1964, 1970), "mean")),
                  dependent = "turnout",
                  unit.variable = "comuna",
                  time.variable = "year",
                  treatment.identifier = 265,
                  controls.identifier = control,
                  time.optimize.ssr = c(1952, 1958, 1964, 1970),
                  time.plot = c(1952, 1958, 1964, 1970,1988))

  synth_out <- synth(data.prep.obj = dataprep_out)
  
  #Turnover graphs: synthetic vs treated comuna 17
  
  #Graph of parallel trends
  path.plot(synth_out,dataprep_out)
  
  #Graph of gap between lines
  gaps.plot(synth_out,dataprep_out)
  
  #Get weights
  synth.tables <- synth.tab(
                          dataprep.res = dataprep_out,
                          synth.res = synth_out) 
  print(synth.tables)
  
  #Inference (get excat p-values)
  placebos <- generate.placebos(dataprep_out, synth_out, Sigf.ipop=3)
  plot_placebos(placebos)
  mspe.plot(placebos, discard.extreme = TRUE, mspe.limit = 1, plot.hist = TRUE)
    #For some counties it doesnt find a synthetic control so it crushes


```

